Repository hufscheer/client, pull requests merged in 2023-11, with the labels that each got.

#30 HOTFIX: 댓글 무한 api 호출 수정
  src/api/game.ts
  src/app/detail/[id]/page.tsx
  src/components/detail/GameComments.tsx
Labels: bug

#39 [BUILD] eslint를 통해 코드 포맷팅 및 컨벤션 강제
  .eslintrc.json
  .prettierrc
  package.json
  src/api/admin.ts
  src/api/auth.ts
  src/api/game.ts
  src/api/team.ts
  src/app/admin/page.tsx
  src/app/detail/[id]/modify/page.tsx
  src/app/detail/[id]/page.tsx
  src/app/detail/[id]/status/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/components/common/Game/GameMain.tsx
  src/components/common/Game/index.ts
  src/components/common/Select/Select.tsx
  src/components/detail/GameComments.tsx
  src/components/detail/GameInfo.tsx
  src/components/detail/GameTimeline.tsx
  src/components/home/GameList/GameWithScore.tsx
  src/components/home/GameList/GameWithTimeStamp.tsx
  src/hooks/useValidate.ts
  yarn.lock
Labels: BUILD

#41 [BUILD]: husky & commitlint로 커밋 메시지 강제
  .commitlintrc.json
  .husky/commit-msg
  .husky/pre-commit
  package.json
  yarn.lock
Labels: BUILD

#42 [CHORE] 타입 컨벤션에 따른 수정
  src/api/admin.ts
  src/api/auth.ts
  src/api/game.ts
  src/api/team.ts
  src/app/admin/page.tsx
  src/app/detail/[id]/modify/page.tsx
  src/app/detail/[id]/page.tsx
  src/app/page.tsx
  src/components/common/Game/GameLive.tsx
  src/components/detail/Comment.tsx
  src/components/detail/GameComments.tsx
  src/components/detail/GameInfo.tsx
  src/components/detail/GameTimeline.tsx
  src/components/detail/Record.tsx
  src/components/home/GameList/GameWithScore.tsx
  src/components/home/GameList/GameWithTimeStamp.tsx
  src/types/admin.ts
  src/types/auth.ts
  src/types/game.ts
Labels: CHORE

#44 [REFACTOR] GAME 합성 컴포넌트를 context api를 활용하여 내부 로직 수정
  .eslintignore
  next.config.js
  package.json
  src/api/admin.ts
  src/api/auth.ts
  src/api/game.ts
  src/api/team.ts
  src/app/admin/page.tsx
  src/app/detail/[id]/modify/page.tsx
  src/app/page.tsx
  src/components/common/Game/GameLabel.tsx
  src/components/common/Game/GameLive.tsx
  src/components/common/Game/GameMain.tsx
  src/components/common/Game/GameScore.tsx
  src/components/common/Game/GameStatus.tsx
  src/components/common/Game/GameTeam.tsx
  src/components/common/Game/GameTeamLogo.tsx
  src/components/common/Game/GameTeamName.tsx
  src/components/common/Game/GameTimer.tsx
  src/components/common/Game/GameWrapper.tsx
  src/components/common/Game/Label.tsx
  src/components/common/Game/Score.tsx
  src/components/common/Game/Status.tsx
  src/components/common/Game/Team.tsx
  src/components/common/Game/index.ts
  src/components/detail/CommentItem.tsx
  src/components/detail/GameInfo.tsx
  src/components/detail/GameTimeline.tsx
  src/components/home/GameItem/index.tsx
  src/components/home/GameList/GameWithScore.tsx
  src/components/home/GameList/GameWithTimeStamp.tsx
  src/constants/gameStatus.ts
  src/hooks/useDate.ts
  src/hooks/useGameContext.ts
  src/types/game.ts
  yarn.lock
Labels: REFACTOR

#46 [BUILD] @tanstack/react-query 설치
  .eslintrc.json
  package.json
  src/app/ReactQueryProvider.tsx
  src/app/layout.tsx
  yarn.lock
Labels: BUILD

#48 [REFACTOR] Tailwindcss 사용성 향상
  .prettierrc
  package.json
  src/app/admin/page.tsx
  src/app/detail/[id]/modify/page.tsx
  src/app/detail/[id]/page.tsx
  src/app/detail/[id]/status/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/Game/GameWrapper.tsx
  src/components/common/Game/Label.tsx
  src/components/common/Game/Score.tsx
  src/components/common/Game/Status.tsx
  src/components/common/Game/Team.tsx
  src/components/common/Input/Input.tsx
  src/components/common/Select/Select.tsx
  src/components/detail/CommentItem.tsx
  src/components/detail/CommentList.tsx
  src/components/detail/GameInfo.tsx
  src/components/detail/Record.tsx
  src/components/home/GameItem/index.tsx
  src/components/home/GameList/GameWithTimeStamp.tsx
  src/utils/core.ts
  yarn.lock
Labels: BUILD

#53 ci: 쉘스크립트 및 yml step 추가
  .github/workflows/ci.yml
  build.sh
Labels: CI

#55 Ci/쉘스크립트 오타 수정
  .github/workflows/ci.yml
  build.sh
Labels: CI

#59 [FIX]: os에 따라 husky가 동작하지 않는 버그 해결
  package.json
Labels: FIX

#62 [CHORE]: 컬러 팔레트 추가
  tailwind.config.ts
Labels: CHORE

#63 [FEAT]: icon 컴포넌트 생성 및 husky 버그 픽스
  .husky/commit-msg
  .husky/pre-commit
  package.json
  src/components/common/Icon/IconMap.ts
  src/components/common/Icon/icon.type.ts
  src/components/common/Icon/index.tsx
Labels: FEAT

#65 [FEAT] icon 컴포넌트 생성
  .husky/commit-msg
  .husky/pre-commit
  package.json
  src/components/common/Icon/IconMap.ts
  src/components/common/Icon/icon.type.ts
  src/components/common/Icon/index.tsx
Labels: FEAT

#73 [CHORE] api 변경에 따른 타입 및 관련 컴포넌트 변경
  src/components/common/Game/index.ts
  src/components/common/Game/pieces/GameWrapper.tsx
  src/components/common/Game/pieces/Label.tsx
  src/components/common/Game/pieces/Score.tsx
  src/components/common/Game/pieces/Status.tsx
  src/components/common/Game/pieces/Team.tsx
  src/hooks/useGameContext.ts
  src/types/game.ts
Labels: CHORE

#71 [FEAT]: 헤더 햄버거 메뉴 구현
  package.json
  src/api/league.ts
  src/components/common/Modal/index.tsx
  src/components/layout/Header.tsx
  tailwind.config.ts
  yarn.lock
Labels: FEAT

#69 [FEAT]: 헤더 타이틀 영역 라우트에 따른 내용물 전환 기능
  package.json
  src/api/league.ts
  src/app/layout.tsx
  src/components/common/Modal/index.tsx
  src/components/common/Sidebar/index.tsx
  src/components/layout/Header.tsx
  tailwind.config.ts
  yarn.lock
Labels: FEAT

#67 [STYLE]: 헤더 기초 UI 디자인
  package.json
  src/api/league.ts
  src/app/layout.tsx
  src/components/common/Modal/index.tsx
  src/components/common/Sidebar/index.tsx
  src/components/layout/Header.tsx
  tailwind.config.ts
  yarn.lock
Labels: STYLE

#75 [REFACTOR] match page 내부 수정 및 리팩토링
  next.config.js
  src/api/admin.ts
  src/api/auth.ts
  src/api/game.ts
  src/api/index.ts
  src/api/match.ts
  src/api/team.ts
  src/app/admin/page.tsx
  src/app/detail/[id]/page.tsx
  src/app/detail/[id]/status/page.tsx
  src/app/match/[id]/modify/page.tsx
  src/app/match/[id]/page.tsx
  src/app/page.tsx
  src/components/common/Game/pieces/GameWrapper.tsx
  src/components/common/Game/pieces/Status.tsx
  src/components/common/Icon/IconMap.ts
  src/components/common/MatchCard/index.ts
  src/components/common/MatchCard/pieces/Label.tsx
  src/components/common/MatchCard/pieces/Score.tsx
  src/components/common/MatchCard/pieces/Status.tsx
  src/components/common/MatchCard/pieces/Team.tsx
  src/components/common/MatchCard/pieces/Wrapper.tsx
  src/components/common/Select/Select.tsx
  src/components/detail/CommentItem.tsx
  src/components/detail/CommentList.tsx
  src/components/detail/GameInfo.tsx
  src/components/detail/GameTimeline.tsx
  src/components/detail/Record.tsx
  src/components/home/GameItem/index.tsx
  src/components/home/GameList/GameWithScore.tsx
  src/components/home/GameList/GameWithTimeStamp.tsx
  src/components/match/Banner/index.tsx
  src/components/match/Cheer/index.tsx
  src/components/match/CheerTeam/index.tsx
  src/hooks/useGameContext.ts
  src/hooks/useMatchCardContext.ts
  src/queries/useMatchById/Fetcher.tsx
  src/queries/useMatchById/query.ts
  src/queries/useMatchCheerById/Fetcher.tsx
  src/queries/useMatchCheerById/query.ts
  src/types/game.ts
  src/types/match.ts
  tailwind.config.ts
Labels: FEAT, REFACTOR

#76 [FEAT] match panel 컴포넌트 생성
  src/api/league.ts
  src/app/match/[id]/page.tsx
  src/components/common/Dropdown/index.tsx
  src/components/common/Dropdown/units/Item.tsx
  src/components/common/Dropdown/units/Menu.tsx
  src/components/common/Dropdown/units/Wrapper.tsx
  src/components/match/LineupItem/index.tsx
  src/components/match/LineupList/index.tsx
  src/components/match/Panel/index.tsx
  src/components/match/RecordItem/index.tsx
  src/components/match/RecordList/index.tsx
  src/components/match/Video/index.tsx
  src/queries/useMatchLineupById/Fetcher.tsx
  src/queries/useMatchLineupById/query.ts
  src/queries/useMatchTimelineById/Fetcher.tsx
  src/queries/useMatchTimelineById/query.ts
  src/types/match.ts
Labels: FEAT

#83 [FEAT] Match VideoId 호출 및 화면에 띄어주기
  src/api/match.ts
  src/app/match/[id]/page.tsx
  src/components/match/Video/index.tsx
  src/constants/videoSrc.ts
  src/queries/useMatchTimelineById/Fetcher.tsx
  src/queries/useMatchTimelineById/query.ts
  src/queries/useMatchVideoById/Fetcher.tsx
  src/queries/useMatchVideoById/query.ts
  src/types/match.ts
Labels: FEAT

#81 [FEAT] Match List 컴포넌트 생성
  src/api/auth.ts
  src/api/match.ts
  src/app/match/[id]/page.tsx
  src/app/page.tsx
  src/components/common/MatchCard/index.ts
  src/components/common/MatchCard/pieces/Background.tsx
  src/components/common/MatchCard/pieces/Label.tsx
  src/components/common/MatchCard/pieces/Wrapper.tsx
  src/components/match/Banner/index.tsx
  src/components/match/MatchList/index.tsx
  src/components/match/Video/index.tsx
  src/constants/videoSrc.ts
  src/hooks/useMatchCardContext.ts
  src/queries/useMatchById/Fetcher.tsx
  src/queries/useMatchList/Fetcher.tsx
  src/queries/useMatchList/query.ts
  src/queries/useMatchTimelineById/Fetcher.tsx
  src/queries/useMatchTimelineById/query.ts
  src/queries/useMatchVideoById/Fetcher.tsx
  src/queries/useMatchVideoById/query.ts
  src/types/match.ts
  src/utils/queryString.ts
Labels: FEAT

#85 [FEAT] useFunnel hook 함수 생성
  src/components/match/MatchList/index.tsx
  src/hooks/useFunnel.tsx
Labels: FEAT

#91 [FEAT] main sports categories 생성
  src/api/league.ts
  src/api/match.ts
  src/app/page.tsx
  src/components/common/Sidebar/index.tsx
  src/components/league/SportsList/index.tsx
  src/hooks/useQueryParams.ts
  src/queries/useSportsListByLeagueId/Fetcher.tsx
  src/queries/useSportsListByLeagueId/query.ts
  src/types/league.ts
Labels: FEAT

#89 [STYLE]: 사이드바 범위 재적용
  src/components/common/Sidebar/index.tsx
  src/components/layout/Header.tsx
Labels: STYLE

#93 [FEAT] 댓글 기능 구현
  package.json
  src/api/match.ts
  src/app/match/[id]/page.tsx
  src/components/common/MatchCard/pieces/Label.tsx
  src/components/match/CommentForm/index.tsx
  src/components/match/CommentItem/index.tsx
  src/components/match/CommentList/index.tsx
  src/hooks/useInfiniteObserver.ts
  src/hooks/useSocket.ts
  src/queries/useMatchCommentById/Fetcher.tsx
  src/queries/useMatchCommentById/query.ts
  src/queries/useReportCommentMutation/query.ts
  src/queries/useSaveCommentMutation/query.ts
  src/types/match.ts
  src/utils/time.ts
  src/utils/utc-times.ts
  yarn.lock
Labels: FEAT

#96 [FEAT] 경기 리스트 무한 스크롤 구현
  src/api/match.ts
  src/app/page.tsx
  src/components/common/Icon/svg/BackgroundLogo.tsx
  src/components/league/SportsList/index.tsx
  src/components/match/MatchList/index.tsx
  src/constants/queryParams.ts
  src/hooks/useQueryParams.ts
  src/queries/useMatchList/Fetcher.tsx
  src/queries/useMatchList/query.ts
  src/types/match.ts
  src/utils/queryString.ts
Labels: FEAT

#99 [FEAT] 에러 처리 및 스켈레톤, 로더 추가
  src/app/match/[id]/page.tsx
  src/app/page.tsx
  src/components/common/AsyncBoundary/index.tsx
  src/components/common/ErrorBoundary/index.tsx
  src/components/common/Loader/index.tsx
  src/components/common/MatchCard/pieces/Label.tsx
  src/components/league/SportsList/index.tsx
  src/components/match/Banner/index.tsx
  src/components/match/Cheer/index.tsx
  src/components/match/CommentList/index.tsx
  src/components/match/LineupList/index.tsx
  src/components/match/MatchList/index.tsx
  src/components/match/RecordList/index.tsx
  src/components/match/Video/index.tsx
  src/constants/error.ts
  src/hooks/useSocket.ts
Labels: FEAT

#102 [FIX] 팀 정보 없을 시 화면이 다운되는 에러 해결
  src/app/match/[id]/page.tsx
  src/components/common/MatchCard/pieces/Label.tsx
  src/components/common/MatchCard/pieces/Score.tsx
  src/components/common/MatchCard/pieces/Team.tsx
  src/components/match/Banner/index.tsx
  src/components/match/CheerTeam/index.tsx
  src/components/match/CommentForm/index.tsx
  src/queries/useMatchCommentById/Fetcher.tsx
  src/queries/useMatchCommentById/query.ts
  src/queries/useMatchList/query.ts
  src/types/match.ts
Labels: FIX

#101 [FEAT]: 리그/팀 등록 및 수정 구현
  .commitlintrc.json
  src/api/admin/league.ts
  src/api/admin/team.ts
  src/app/admin/page.tsx
  src/app/admin/register/[leagueId]/page.tsx
  src/app/admin/register/page.tsx
  src/components/admin/register/League/index.tsx
  src/components/admin/register/Team/index.tsx
  src/components/admin/register/context/RegisterWrapper.tsx
  src/components/admin/register/context/wrapper.type.ts
  src/components/common/Checkbox/Item.tsx
  src/components/common/Icon/IconMap.ts
  src/components/common/Icon/svg/CheckCircled.tsx
  src/hooks/useDate.ts
  src/hooks/useFunnel.tsx
  src/hooks/useLeagueIdContext.ts
  src/hooks/useValidate.ts
  src/queries/admin/useLeagueRegister/Fetcher.tsx
  src/queries/admin/useLeagueRegister/query.ts
  src/queries/admin/useTeamRegister/Fetcher.tsx
  src/queries/admin/useTeamRegister/query.ts
  src/types/admin/team.ts
  src/utils/set.ts
Labels: FEAT

#100 [FEAT]: `/admin/league` 라우트 구현
  .commitlintrc.json
  src/api/admin/league.ts
  src/api/admin/team.ts
  src/app/admin/league/page.tsx
  src/app/admin/page.tsx
  src/app/admin/register/[leagueId]/page.tsx
  src/app/admin/register/page.tsx
  src/components/admin/league/LeagueList/index.tsx
  src/components/admin/register/League/index.tsx
  src/components/admin/register/Team/index.tsx
  src/components/admin/register/context/RegisterWrapper.tsx
  src/components/admin/register/context/wrapper.type.ts
  src/components/common/Button/index.tsx
  src/components/common/Card/index.tsx
  src/components/common/Card/league/Content.tsx
  src/components/common/Checkbox/Item.tsx
  src/components/common/Icon/IconMap.ts
  src/components/common/Icon/svg/CheckCircled.tsx
  src/constants/adminDescription.ts
  src/hooks/useDate.ts
  src/hooks/useFunnel.tsx
  src/hooks/useLeagueIdContext.ts
  src/hooks/useScrollLock.ts
  src/hooks/useValidate.ts
  src/queries/admin/useLeagueList/Fetcher.tsx
  src/queries/admin/useLeagueList/query.ts
  src/queries/admin/useLeagueRegister/Fetcher.tsx
  src/queries/admin/useLeagueRegister/query.ts
  src/queries/admin/useTeamRegister/Fetcher.tsx
  src/queries/admin/useTeamRegister/query.ts
  src/types/admin/league.ts
  src/types/admin/team.ts
  src/utils/set.ts
Labels: FEAT

#103 [REFACTOR]: login 리팩토링
  src/app/login/page.tsx
  src/components/common/Icon/iconMap.ts
  src/queries/admin/useLeagueList/query.ts
  src/queries/useLogin/query.ts
Labels: REFACTOR

#108 [FEAT] Vercel Analytics 설치 및 세팅
  package.json
  src/app/layout.tsx
  yarn.lock
Labels: FEAT

#110 [CHORE]: 훕스트리밍 -> 훕치치 메타데이터 최신화
  public/icon_hufscheer.svg
  public/icon_hufstreaming.svg
  public/logo_hufstreaming.png
  src/app/layout.tsx
Labels: CHORE

#111 [FIX] 필요한 변경 사항을 모두 수정합니다.
  next.config.js
  src/api/match.ts
  src/app/match/[id]/page.tsx
  src/app/rummikube/[id]/page.tsx
  src/components/match/Cheer/index.tsx
  src/components/match/CheerTeam/index.tsx
  src/components/match/CommentForm/index.tsx
  src/components/match/CommentItem/index.tsx
  src/components/match/Video/index.tsx
  src/components/rummikub/Cheer/index.tsx
  src/components/rummikub/MatchBanner/index.tsx
  src/components/rummikub/MatchItem/index.tsx
  src/hooks/useQueryDebounce.ts
  src/queries/useCheerMutation/query.ts
  src/queries/useMatchCheerById/Fetcher.tsx
  src/queries/useMatchCheerById/query.ts
  src/queries/useMatchVideoById/Fetcher.tsx
  src/utils/queryString.ts
Labels: FIX

#112 Fix/cheer delay
  src/app/page.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/match/CheerTeam/index.tsx
  src/components/match/CommentForm/index.tsx
Labels: FIX

#114 [FEAT] google analytics 추가
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/match/CheerTeam/index.tsx
  src/components/match/CommentForm/index.tsx
  src/types/ga/gtag.ts
Labels: FEAT

#115 [FEAT] google analytics 추가
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/layout.tsx
  src/types/ga/gtag.ts
Labels: FEAT

#116 [FIX]: 서버 컴포넌트에서 useEffect가 안돌아가는 문제 해결
  package.json
  src/app/GoogleAnalytics.tsx
  src/app/layout.tsx
  src/types/ga/gtag.ts
  src/types/type.d.ts
  src/utils/gtag.ts
  yarn.lock
Labels: FIX

#117 [FIX] 경기 시간의 분을 두자리로 출력
  src/api/match.ts
  src/app/page.tsx
  src/components/common/MatchCard/pieces/Label.tsx
  src/components/common/Sidebar/index.tsx
  src/components/match/CommentForm/index.tsx
  src/constants/queryParams.ts
  src/queries/useMatchList/Fetcher.tsx
  src/queries/useMatchList/query.ts
  src/queries/useSportsListByLeagueId/Fetcher.tsx
Labels: FIX

#118 fix: value가 없을 땐 query string 넘기지 않도록 수정
  src/utils/queryString.ts
Labels: FIX

#119 [REFACTOR]: 관리자 리그 쿼리, 스크롤락, 리그 삭제 버그픽스
  src/app/admin/league/page.tsx
  src/app/admin/register/[leagueId]/page.tsx
  src/app/admin/register/page.tsx
  src/components/admin/league/LeagueList/index.tsx
  src/components/admin/register/League/edit/index.tsx
  src/components/admin/register/League/index.tsx
  src/components/admin/register/Team/index.tsx
  src/constants/admin/description.ts
  src/constants/admin/mutationKey.ts
  src/constants/admin/queryKey.ts
  src/hooks/useScrollLock.ts
  src/queries/admin/league/useDeleteLeagueMutation/index.ts
  src/queries/admin/league/useLeagueList/Fetcher.tsx
  src/queries/admin/league/useLeagueList/query.ts
  src/queries/admin/league/useLeagueRegister/Fetcher.tsx
  src/queries/admin/league/useLeagueRegister/query.ts
  src/queries/admin/league/usePostNewLeagueMutation/index.ts
  src/queries/admin/league/usePutLeagueMutation/index.ts
  src/queries/admin/team/usePostTeamMutation/index.ts
  src/queries/admin/team/useTeamRegister/Fetcher.tsx
  src/queries/admin/team/useTeamRegister/query.ts
  src/queries/admin/useLeagueList/query.ts
  src/queries/admin/useLeagueRegister/query.ts
  src/queries/admin/useTeamRegister/query.ts
Labels: REFACTOR

#120 [FEAT] fconline 전용 컴포넌트 생성
  src/api/player..ts
  src/app/match/[id]/page.tsx
  src/components/fcOnline/UserInfo/index.tsx
  src/constants/divisionRank.ts
  src/queries/useFconlineLineupById/Fetcher.tsx
  src/queries/useFconlineLineupById/query.ts
  src/types/match.ts
Labels: FEAT

#121 [FIX] value가 비었을 때 댓글이 등록되지 않도록 수정
  src/components/match/CommentForm/index.tsx
Labels: FIX
